schema_version = "1.1"

[task]
name = "tmax/task_000259_03738832"
description = "data scientist cleaning datasets"

[metadata]
source = "legacy"
base_image = ""
domain = "data_science"
skill_type = "Testing"
primitive_skills = ["Multi-source data joining", "Sampling and bootstrap methods", "Linear algebra for data analysis", "Inference performance benchmarking", "Tabular data transformation and aggregation"]
task_complexity = "complex task (many commands spanning multiple phases: dependency installation, code writing, configuration, building, and testing)"
command_complexity = "bash and code (shell commands and writing/running scripts in Python, Perl, Ruby, etc.)"
scenario = "data scientist cleaning datasets"
language = "Bash"

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 120.0

[environment]
docker_image = "tmax/task_000259_03738832:latest"
cpus = 1
memory_mb = 2048
allow_internet = true
