schema_version = "1.1"

[task]
name = "tmax/task_001353_e7085fc8"
description = "performance engineer profiling applications"

[metadata]
source = "legacy"
base_image = ""
domain = "scientific_computing"
skill_type = "Statistical"
primitive_skills = ["Numerical integration and differentiation", "Scientific data format I/O (NetCDF, HDF5, FITS)", "Mesh refinement and domain decomposition", "Multi-dimensional array manipulation"]
task_complexity = "short task (a few shell commands focused on the core task)"
command_complexity = "bash and code (shell commands and writing/running scripts in Python, Perl, Ruby, etc.)"
scenario = "performance engineer profiling applications"
language = "Python"

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 120.0

[environment]
docker_image = "tmax/task_001353_e7085fc8:latest"
cpus = 1
memory_mb = 2048
allow_internet = true
